// The site's own UI chrome — the in-code i18n map (per CLAUDE.md: chrome copy is in-code, not
// the DB) — beside the design copy in `design.ts`. Both are read through `lib/copy` only: on the
// server by `translator`, and in the browser as the ONE locale the page renders, handed down by the
// root layout (C-56). Keep keys flat and stable; a key nothing reads is deleted, not kept "in case".
import type { Locale } from "@/lib/i18n";

type Dict = Record<string, string>;

const fa: Dict = {
  "nav.home": "خانه",
  nav_contact: "تماس",
  "nav.getConfig": "دریافت کانفیگ",
  "status.noHistory": "هنوز تاریخچه‌ای نیست",
  "status.noHistorySub": "بعد از اولین دریافت این‌جا پر می‌شود.",
  "status.offline": "اتصال به سرور برقرار نشد — دادهٔ زندهٔ مصرف در دسترس نیست.",
  "transfer.generate": "ساخت کد انتقال",
  "contact.title": "تماس با ما",
  "contact.sub": "سوال یا مشکلی داری؟ برایمان بنویس.",
  "contact.about": "می‌خواهی بدانی گذرایکس چیست و چطور رایگان می‌ماند؟",
  crumbs: "مسیر صفحه",
  hide_qr: "بستن کد QR",
  qr_alt: "کد QR لینک کانفیگ",
  qr_hint: "با گزینهٔ «اسکن QR» در اپت اسکنش کن.",
  qr_failed: "کد QR ساخته نشد؛ لینک را کپی کن.",
  set_notif_blocked: "در تنظیمات مرورگر مسدود شده؛ تا آزادش نکنی اعلانی نمی‌رسد.",
  set_notif_how: "چطور آزادش کنم؟",
  set_notif_ios: "روی آیفون، اعلان فقط در وب‌اپ نصب‌شده کار می‌کند.",
  set_notif_install: "مراحل نصب",
  set_notif_unsupported: "این مرورگر اعلان وب را پشتیبانی نمی‌کند.",
  restore_warn:
    "این مرورگر به دستگاهی که کد را ساخته وصل می‌شود. کانفیگ، سوابق و دعوت‌های فعلیِ همین مرورگر دیگر این‌جا دیده نمی‌شوند.",
  restore_go: "بله، وصل کن",
  "contact.error": "ارسال نشد. لطفاً دوباره تلاش کن.",
  "offline.title": "آفلاین هستی",
  "offline.sub": "اتصال اینترنت برقرار نیست. آخرین کانفیگ ذخیره‌شده‌ات این‌جاست.",
  "offline.none":
    "اتصال اینترنت برقرار نیست. هنوز کانفیگی روی این مرورگر ذخیره نشده؛ وقتی آنلاین شدی یکی بگیر تا این‌جا هم در دسترس باشد.",
  "offline.saved": "آخرین کانفیگ",
  "offline.until": "معتبر تا {t}",
  "offline.expired": "زمان این کانفیگ احتمالاً تمام شده؛ وقتی آنلاین شدی، کانفیگ تازه بگیر.",
  "offline.copy": "کپی لینک",
  "offline.retry": "تلاش دوباره",
  "notfound.title": "صفحه پیدا نشد",
  "notfound.sub": "شاید آدرس عوض شده یا اشتباه تایپ شده. از یکی از این‌ها ادامه بده:",
  "notfound.search": "در سوالات متداول جستجو کن…",
  "notfound.go": "جستجو",
  "notfound.home": "بازگشت به خانه",
  "err.title": "این صفحه درست باز نشد",
  "err.sub": "مشکل از سمت ما بود، نه تو. دوباره امتحان کن؛ اگر درست نشد، از صفحهٔ اصلی ادامه بده.",
  "common.close": "بستن",
  menu_open: "باز کردن منو",
  menu_title: "منوی سایت",
  tm_gen_err: "ساخت کد انجام نشد. چند دقیقهٔ دیگر دوباره امتحان کن.",
  invite_copied: "لینک دعوت کپی شد",
  reward_added: "{v} به حجم روزانه‌ات اضافه شد",
  reward_taken: "این جایزه را قبلاً گرفته‌ای.",
  reward_err: "ثبت جایزه انجام نشد — دوباره تلاش کن.",
  usage_none: "هنوز مصرفی نداشتی",
  cta_verifying: "در حال بررسی امنیتی…",
  cta_slow: "کمی بیشتر طول کشید؛ هنوز در حال ساخت است…",
  notice_loc_gone: "این لوکیشن دیگر در دسترس نیست. فهرست تازه شد؛ یکی دیگر انتخاب کن.",
  notice_busy: "درخواست قبلی‌ات هنوز در جریان است؛ چند ثانیهٔ دیگر دوباره بزن.",
  notice_ts: "بررسی امنیتی باید دوباره انجام شود؛ یک لحظه صبر کن و دوباره بزن.",
  blk_title: "این دستگاه کانفیگ رایگان نمی‌گیرد",
  blk_sub: "دریافت کانفیگ برای این دستگاه بسته شده است. اگر فکر می‌کنی اشتباهی پیش آمده، برایمان بنویس.",
  blk_contact: "تماس با ما",
  revived_title: "کانفیگت دوباره زنده شد ✨",
  revived_sub: "همین لینک دوباره کار می‌کند؛ لازم نیست چیزی را عوض کنی.",
  revived_friend: "یک دوست دعوتت را پذیرفت و {v} به حجم روزانه‌ات اضافه شد.",
  change_to: "تغییر به {loc}",
  change_pick: "یک لوکیشن دیگر انتخاب کن",
  chg_cancel: "انصراف",
  loc_current: "فعلی",
  loc_more_all: "همهٔ لوکیشن‌ها ({n})",
  app_get: "اپ را نداری؟ نصبش کن",
  m_pwa_ios: "روی آیفون اعلان‌ها هم فقط بعد از نصب کار می‌کنند",
  invite_share: "کانفیگ رایگان روزانه، بدون ثبت‌نام 🎁 با لینک من بگیر:",
  ref_welcome: "دوستت دعوتت کرده 🎁 کانفیگ رایگانت را بگیر؛ با اولین دریافتت، به دوستت هم حجم هدیه می‌رسد.",
  sticky_get: "دریافت کانفیگ رایگان",
  sticky_mine: "کانفیگ من",
  land_w_title: "کانفیگ رایگان {loc}",
  land_cta_h: "کانفیگ رایگان {loc} را همین حالا بگیر",
  land_cta_h_any: "کانفیگ رایگان امروزت را همین حالا بگیر",
  land_cta_d: "بدون ثبت‌نام؛ کمتر از یک دقیقه تا اتصال.",
  ft_cta_inv_h: "دوستانت را دعوت کن",
  ft_cta_inv_d: "هر دعوت موفق {v} به حجم روزانه‌ات اضافه می‌کند.",
  ft_cta_inv_d_any: "با هر دعوت موفق حجم روزانه‌ات بیشتر می‌شود.",
  ft_cta_inv_btn: "دعوت دوستان",
  ft_cta_mine_h: "همه‌چیزِ کانفیگت یک‌جا",
  app_desktop: "دسکتاپ",
  skip_main: "پرش به محتوا",
  menu_close: "بستن منو",
  theme_sys: "سیستم",
  ft_cta_mine_d: "مصرف، زمان باقی‌مانده و جایزه‌هایت در صفحهٔ کانفیگ من است.",
  art_all: "همهٔ مقاله‌ها",
  art_read: "خواندن",
  art_page_title: "راهنماها و مقاله‌ها",
  art_page_sub: "آموزش اتصال با اپ‌های مختلف و پاسخ پرسش‌های رایج دربارهٔ کانفیگ رایگان.",
  art_empty: "فعلاً مقاله‌ای برای نمایش نیست؛ کمی بعد دوباره سر بزن.",
};

const en: Dict = {
  "nav.home": "Home",
  nav_contact: "Contact",
  "nav.getConfig": "Get config",
  "status.noHistory": "No history yet",
  "status.noHistorySub": "It fills up after your first claim.",
  "status.offline": "Couldn't reach the server — live usage is unavailable.",
  "transfer.generate": "Generate transfer code",
  "contact.title": "Contact us",
  "contact.sub": "Got a question or issue? Write to us.",
  "contact.about": "Want to know what GozarX is and how it stays free?",
  crumbs: "Breadcrumb",
  hide_qr: "Hide QR code",
  qr_alt: "QR code of the config link",
  qr_hint: "Scan it with the “Scan QR” option in your app.",
  qr_failed: "Couldn't draw the QR code — copy the link instead.",
  set_notif_blocked: "Blocked in your browser's settings — nothing arrives until you allow it.",
  set_notif_how: "How do I allow it?",
  set_notif_ios: "On iPhone, notifications only work in the installed web app.",
  set_notif_install: "How to install",
  set_notif_unsupported: "This browser doesn't support web notifications.",
  restore_warn:
    "This browser will be linked to the device that made the code. Its current config, history and invites will no longer show here.",
  restore_go: "Yes, link it",
  "contact.error": "Couldn't send. Please try again.",
  "offline.title": "You're offline",
  "offline.sub": "No internet connection. Here's your last saved config.",
  "offline.none":
    "No internet connection. No config is saved on this browser yet — claim one once you're online and it will be here too.",
  "offline.saved": "Last config",
  "offline.until": "Valid until {t}",
  "offline.expired": "This config has probably run out — claim a fresh one once you're online.",
  "offline.copy": "Copy link",
  "offline.retry": "Try again",
  "notfound.title": "Page not found",
  "notfound.sub": "The address may have changed or been mistyped. Carry on from one of these:",
  "notfound.search": "Search the FAQ…",
  "notfound.go": "Search",
  "notfound.home": "Back home",
  "err.title": "This page didn't load properly",
  "err.sub": "The problem was on our side, not yours. Try again — if it still fails, carry on from the home page.",
  "common.close": "Close",
  menu_open: "Open menu",
  menu_title: "Site menu",
  tm_gen_err: "Couldn't create a code. Try again in a few minutes.",
  invite_copied: "Invite link copied",
  reward_added: "{v} added to your daily volume",
  reward_taken: "You've already claimed this reward.",
  reward_err: "Couldn't add the reward — please try again.",
  usage_none: "Nothing used yet",
  cta_verifying: "Running a security check…",
  cta_slow: "Taking a little longer — still building it…",
  notice_loc_gone: "That location isn't available any more. The list is refreshed — pick another.",
  notice_busy: "Your previous request is still running — try again in a few seconds.",
  notice_ts: "The security check has to run again — wait a moment, then try again.",
  blk_title: "This device can't get a free config",
  blk_sub: "Free configs are switched off for this device. If you think that's a mistake, write to us.",
  blk_contact: "Contact us",
  revived_title: "Your config is back ✨",
  revived_sub: "The same link works again — nothing to change.",
  revived_friend: "A friend accepted your invite, and {v} was added to your daily volume.",
  change_to: "Switch to {loc}",
  change_pick: "Pick a different location",
  chg_cancel: "Cancel",
  loc_current: "Current",
  loc_more_all: "All locations ({n})",
  app_get: "Don't have the app? Install it",
  m_pwa_ios: "On iPhone, notifications need the installed app too",
  invite_share: "A free daily config, no signup 🎁 Grab yours with my link:",
  ref_welcome: "A friend invited you 🎁 Claim your free config — your first claim sends them bonus volume too.",
  sticky_get: "Get a free config",
  sticky_mine: "My config",
  land_w_title: "Free {loc} config",
  land_cta_h: "Get your free {loc} config now",
  land_cta_h_any: "Get today's free config now",
  land_cta_d: "No signup — under a minute to connect.",
  ft_cta_inv_h: "Invite your friends",
  ft_cta_inv_d: "Each successful invite adds {v} to your daily volume.",
  ft_cta_inv_d_any: "Each successful invite grows your daily volume.",
  ft_cta_inv_btn: "Invite friends",
  ft_cta_mine_h: "Everything about your config, in one place",
  app_desktop: "Desktop",
  skip_main: "Skip to content",
  menu_close: "Close menu",
  theme_sys: "System",
  ft_cta_mine_d: "Your usage, time left and rewards are on your config page.",
  art_all: "All articles",
  art_read: "Read",
  art_page_title: "Guides and articles",
  art_page_sub: "How to connect with each app, and answers to common questions about free configs.",
  art_empty: "No articles to show right now — check back soon.",
};

export const CHROME: Record<Locale, Dict> = { fa, en };
