// The design copy: verbatim from the Phase 0-8 design artifacts' i18n dictionaries
// (docs/website/design), keyed by the design's own flat keys (e.g. hero_h1_a, cta_get), then edited
// here as the site grew. Pruned to the keys the site reads (C-56) — the artifacts' copy for pages
// that were never built (the blog, the gauge, the review gallery, the dev bar) rode in every
// visitor's bundle. The panel-editable subset is mirrored by `SITE_COPY_DEFAULTS` in
// backend/gozar/services/site_copy_keys.py; keep the two in step.
import type { Locale } from "@/lib/i18n";

export const DESIGN_COPY: Record<Locale, Record<string, string>> = {
  fa: {
    nav_loc: "لوکیشن‌ها",
    nav_guides: "راهنما",
    nav_faq: "سوالات",
    nav_status: "کانفیگ من",
    hero_eyebrow: "کانفیگ رایگان روزانه",
    hero_h1_a: "کانفیگ رایگان و پرسرعت،",
    hero_h1_b: "در چند ثانیه",
    hero_sub: "هر روز یک کانفیگ آزمایشی رایگان بگیر؛ لوکیشن دلخواهت را انتخاب کن و بدون ثبت‌نام وصل شو. با دعوت دوستان هم حجم روزانه‌ات بیشتر می‌شود.",
    hero_sub_short: "هر روز یک کانفیگ رایگان؛ بدون ثبت‌نام، با لوکیشن دلخواه.",
    trust1: "بدون ثبت‌نام",
    trust2: "همیشه رایگان",
    trust3: "هر {h} ساعت تازه",
    trust4: "+{n} کانفیگ تحویل‌شده",
    w_title: "کانفیگ رایگان امروز",
    w_sub: "یک لوکیشن انتخاب کن و بگیر",
    allowance: "{v} امروز",
    pick: "لوکیشن را انتخاب کن",
    pick_count: "{n} لوکیشن",
    rec: "محبوب",
    cta_get: "دریافت کانفیگ",
    cta_prep: "در حال آماده‌سازی کانفیگ…",
    reassure1: "بدون ثبت‌نام",
    reassure2: "رایگان",
    reassure3: "هر {h} ساعت تازه",
    antibot: "با یک بررسی نامرئی در برابر ربات محافظت می‌شود",
    ts_fail: "بررسی امنیتی بارگذاری نشد — اتصالت را بررسی کن.",
    ts_retry: "تلاش دوباره",
    succ_title: "کانفیگ آماده است",
    succ_sub: "لینک را کپی کن یا در اپ باز کن.",
    ready: "آماده",
    link_label: "لینک کانفیگ",
    copy: "کپی",
    copied: "کپی شد",
    copy_manual: "کپی نشد — متن انتخاب شد، دستی کپی کن.",
    show_qr: "کد QR",
    app_hint: "برای افزودن سریع کانفیگ، اپ موردنظرت را بزن.",
    time_left: "زمان باقی‌مانده",
    usage: "مصرف امروز",
    of: "از",
    remaining_vol: "مانده:",
    cd_h: "ساعت",
    cd_m: "دقیقه",
    cd_s: "ثانیه",
    m_title: "حجم بیشتری می‌خواهی؟",
    m_invite: "دعوت دوستان",
    m_invite_d: "به‌ازای هر دعوت موفق",
    m_of: "از", // invite progress: "<n> از <cap> دعوت"
    m_invites: "دعوت",
    m_pwa: "نصب وب‌اپ",
    m_pwa_d: "یک‌بار، همیشگی",
    m_pwa_done: "نصب‌شده روی این دستگاه",
    m_push: "روشن‌کردن اعلان‌ها",
    m_push_d: "یک‌بار",
    m_push_done: "اعلان‌ها روشن است",
    how_eyebrow: "سه قدم ساده",
    how_title: "چطور کار می‌کند؟",
    how_sub: "از ورود تا اتصال، کمتر از یک دقیقه.",
    how1_t: "لوکیشن را انتخاب کن",
    how1_d: "از میان لوکیشن‌هایی که همین حالا ارائه می‌شوند، یکی را بزن.",
    how2_t: "کانفیگ را بگیر",
    how2_d: "دکمهٔ دریافت را بزن؛ کانفیگ در چند ثانیه ساخته می‌شود — بدون ثبت‌نام.",
    how3_t: "در اپ وارد کن",
    how3_d: "لینک را کپی کن یا QR را اسکن کن و در اپ مخصوص دستگاهت وارد شو.",
    loc_eyebrow: "لوکیشن‌ها",
    loc_title: "از هر کشوری که بخواهی",
    loc_sub: "کانفیگ {locs} — همه رایگان و روزانه.",
    loc_all: "مشاهدهٔ همهٔ لوکیشن‌ها",
    loc_go: "دریافت",
    loc_active: "لوکیشن فعال",
    loc_worldwide: "سرورهای فعال در نقاط مختلف جهان برای اینترنت آزاد و بدون مرز.",
    // /locations index page + /l/{slug} SEO landings
    loc_page_title: "لوکیشن‌های کانفیگ رایگان",
    loc_page_sub: "سرور کشور دلخواهت را انتخاب کن — کانفیگ اختصاصی، روزانه و بدون ثبت‌نام.",
    // `{locs}` is the squad's live list, read server-side; without it the sentence drops that clause
    // (loc_page_p1_any) rather than name countries nobody checked were served.
    loc_page_p1:
      "گذرایکس همین حالا این لوکیشن‌ها را ارائه می‌دهد: {locs}. برای هر کانفیگ، خودت لوکیشن را انتخاب می‌کنی و هر روز می‌توانی کشور را عوض کنی — بدون هزینه و بدون ثبت‌نام.",
    loc_page_p1_any:
      "برای هر کانفیگ، خودت لوکیشن را انتخاب می‌کنی و هر روز می‌توانی کشور را عوض کنی — بدون هزینه و بدون ثبت‌نام.",
    loc_page_p2:
      "انتخاب کشور به نیازت بستگی دارد: برای پینگ پایین سراغ کشورهای نزدیک برو و برای دسترسی به سرویس‌های خاص، کشور همان سرویس را انتخاب کن. راهنمای بعضی از پرطرفدارترین لوکیشن‌ها را در ادامه ببین.",
    loc_page_grid: "همهٔ لوکیشن‌های فعال",
    loc_page_guides: "راهنمای لوکیشن‌های پرطرفدار",
    land_home: "خانه",
    land_related: "صفحات مرتبط",
    // homepage "articles & guides" band + the footer's article row (internal links to /l/*)
    art_eyebrow: "مقاله و راهنما",
    art_title: "راهنماها و مقالات",
    art_sub: "آموزش اتصال با برنامه‌های مختلف و پاسخ پرسش‌های رایج دربارهٔ کانفیگ رایگان.",
    ft_articles: "راهنماها و مقالات",
    chg_more: "{n} لوکیشن دیگر در دسترس",
    // rewards card (account) — daily-rewards redesign
    rw_sub: "ماموریت‌ها را کامل کن و حجم روزانه‌ات را بیشتر کن.",
    rw_day: "روز {a} از {b}",
    rw_keep: "روزهای پیاپی‌ات را ادامه بده!",
    rw_claimed: "امروز گرفتی — فردا:",
    rw_day_n: "روز {n}",
    rw_claim_now: "امروز کانفیگت را بگیر تا روزهای پیاپی‌ات ادامه پیدا کند.",
    rw_full: "روزهای پیاپی کامل شد — جایزه روی حجم روزانه‌ات فعال است.",
    rw_completed: "تکمیل شد",
    rw_available: "در دسترس",
    rw_blocked: "مسدود شده",
    rw_foot: "ماموریت‌های کامل‌شدهٔ بیشتر = حجم روزانهٔ بیشتر.",
    rw_pwa_d: "وب‌اپ GozarX را روی همین دستگاه نصب کن.",
    rw_push_d: "اجازهٔ اعلان مرورگر را فعال کن.",
    rw_push_err: "فعال‌سازی اعلان انجام نشد — دوباره تلاش کن.",
    mv_eyebrow: "حجم بیشتر، رایگان",
    mv_title: "حجم روزانه‌ات را بیشتر کن",
    mv_sub: "چند کار ساده انجام بده و حجم روزانه‌ات را چند برابر کن — همه بدون پرداخت.",
    mv_all: "مشاهدهٔ همهٔ ماموریت‌ها",
    mv1_t: "دعوت دوستان",
    mv1_d: "به‌ازای هر دوست که کانفیگ بگیرد، حجم روزانه‌ات بیشتر می‌شود.",
    mv2_t: "نصب وب‌اپ",
    mv2_d: "وب‌اپ را روی دستگاهت نصب کن و حجم هدیه بگیر.",
    mv3_t: "روشن‌کردن اعلان‌ها",
    mv3_d: "اعلان‌ها را فعال کن تا از کانفیگ آماده باخبر شوی.",
    mv4_t: "ورود روزانه",
    mv4_d: "چند روز پیاپی سر بزن و جایزه بگیر.",
    app_eyebrow: "اپ‌های سازگار",
    app_title: "با اپ دلخواهت وصل شو",
    app_sub: "کانفیگ در Happ، v2rayNG و Streisand کار می‌کند. راهنمای اپ دستگاهت را باز کن.",
    app_rec: "پیشنهادی",
    stat1: "کانفیگ تحویل‌شده",
    stat2: "لوکیشن فعال",
    stat3: "پایداری سرویس",
    faq_eyebrow: "سوالات متداول",
    faq_title: "سوالی داری؟",
    faq_all: "مشاهدهٔ همهٔ سوالات",
    trust_title: "بدون ثبت‌نام. بدون ردگیری تبلیغاتی.",
    trust_sub: "برای دریافت کانفیگ هیچ حساب، ایمیل یا شماره‌ای لازم نیست. هویت فقط با یک شناسهٔ سبک روی همین مرورگر ساخته می‌شود.",
    trust_link: "دربارهٔ حریم خصوصی بخوان",
    tb1: "بدون ایمیل",
    tb2: "بدون شماره",
    tb3: "بدون ثبت‌نام",
    ft_tag: "کانفیگ آزمایشی رایگان روزانه، برای همه — بدون ثبت‌نام، سریع و ساده.",
    ftc_product: "محصول",
    ftc_resources: "منابع",
    ftc_legal: "قانونی",
    ft_get: "دریافت کانفیگ",
    ft_loc: "لوکیشن‌ها",
    ft_rewards: "حجم بیشتر",
    ft_status: "کانفیگ من",
    ft_guides: "راهنمای اتصال",
    ft_faq: "سوالات متداول",
    ft_about: "دربارهٔ ما",
    ft_terms: "قوانین استفاده",
    ft_privacy: "حریم خصوصی",
    ft_contact: "تماس با ما",
    ft_rights: "همهٔ حقوق محفوظ است.", // copyright year is prepended dynamically
    ft_cta_h: "هنوز کانفیگ امروزت را نگرفته‌ای؟",
    ft_cta_d: "رایگان، روزانه و بدون ثبت‌نام — کمتر از یک دقیقه تا اتصال.",
    ft_cta_btn: "دریافت کانفیگ رایگان",
    active_title: "کانفیگت فعال است",
    active_sub: "می‌توانی کپی کنی یا لوکیشن را عوض کنی.",
    change_loc: "تغییر لوکیشن",
    cd_title: "کانفیگ امروزت را گرفتی",
    cd_sub: "به‌محض پایان شمارش، کانفیگ تازه بگیر.",
    cd_next: "کانفیگ بعدی تا",
    ex_title: "حجم امروزت تمام شد",
    ex_sub: "زمان کانفیگ باقی است، فقط حجمش تمام شده.",
    revive_t: "همین کانفیگ را زنده کن",
    revive_d: "فقط <b>یک دوست</b> را دعوت کن؛ به‌محض اینکه اولین کانفیگش را بگیرد، همین کانفیگ تو <b>همان لحظه</b> دوباره فعال می‌شود — بدون صبرکردن تا فردا.",
    invite_label: "لینک دعوت تو",
    share: "اشتراک‌گذاری",
    revived: "یک دوست دعوتت را پذیرفت — کانفیگ دوباره فعال شد! ✨",
    empty_title: "لوکیشن‌ها در حال به‌روزرسانی‌اند",
    empty_sub: "هنوز لوکیشنی آماده نیست. چند دقیقهٔ دیگر دوباره سر بزن.",
    empty_link: "مشاهدهٔ سوالات متداول",
    err_title: "یک وقفهٔ کوتاه پیش آمد",
    err_sub: "نگران نباش، دریافت تو دست‌نخورده مانده. یک‌بار دیگر تلاش کن.",
    err_retry: "تلاش دوباره",
    err_help: "راهنما و پشتیبانی",
    title: "کانفیگ من",
    acc_transfer: "انتقال",
    acc_cap: "شناسهٔ عمومی تو · روی این مرورگر ذخیره می‌شود",
    hist_title: "تاریخچهٔ دریافت",
    set_title: "تنظیمات",
    set_lang: "زبان",
    set_theme: "تم",
    set_theme_l: "روشن",
    set_theme_d: "تاریک",
    set_notif: "اعلان‌ها",
    set_notif_d: "از آماده‌شدن کانفیگ و کم‌شدن حجم باخبر شو",
    perm_denied: "مسدود در مرورگر",
    perm_granted: "فعال",
    danger_t: "پاک‌کردن دادهٔ این دستگاه",
    danger_d: "سوابق، حجم و دعوت‌های این مرورگر پاک می‌شود. برگشت‌پذیر نیست.",
    danger_btn: "پاک‌کردن داده",
    restore_t: "قبلاً از GozarX استفاده کرده‌ای؟",
    restore_d: "اگر روی دستگاه دیگری کد انتقال ساخته‌ای، این‌جا واردش کن تا سوابق و دعوت‌هایت برگردد.",
    restore_ph: "کد ۸ کاراکتری",
    restore_btn: "بازیابی سوابق",
    restore_err: "کد نادرست یا منقضی است. دوباره بررسی کن.",
    tm_gen_title: "انتقال به دستگاه دیگر",
    tm_gen_sub: "این کد را روی دستگاه جدید وارد کن تا سوابق، حجم و دعوت‌هایت منتقل شود. کد یک‌بارمصرف است.",
    tm_expiry: "زمان باقی‌مانده:",
    tm_copy: "کپی کد",
    rm_t: "مطمئنی؟",
    rm_p: "همهٔ سوابق، حجم و دعوت‌های این مرورگر پاک می‌شود. این کار برگشت‌پذیر نیست.",
    rm_cancel: "انصراف",
    rm_confirm: "بله، پاک کن",
    reset_done: "دادهٔ دستگاه پاک شد.",
    restored: "سوابقت بازیابی شد! ✨",
    revive: "اگر حجم امروزت تمام شود، فقط <b>یک دعوت موفق</b> کافی است تا همان کانفیگ <b>همان لحظه</b> دوباره زنده شود.",
    claim: "دریافت پاداش",
    home: "خانه",
    v_contact: "تماس",
    medium: "متوسط",
    faq_sub: "پاسخ سریع به پرتکرارترین سوال‌ها. اگر جوابت این‌جا نبود، از صفحهٔ تماس بپرس.",
    // /about (the contact page has its own heading now — they were one page with two URLs)
    about_eyebrow: "گذرایکس",
    about_title: "دربارهٔ ما",
    about_mission_h: "هدف ما",
    about_free_h: "چطور رایگان می‌ماند؟",
    about_free_body:
      "دریافت کانفیگ هیچ پرداختی نمی‌خواهد و هیچ مرحلهٔ پولی ندارد. هر کانفیگ آزمایشی است: مدت و حجم روزانهٔ مشخصی دارد و وقتی تمام شد، کانفیگ تازه می‌گیری. حجم بیشتر را هم با دعوت دوستان و ماموریت‌های سایت می‌گیری، نه با پرداخت.",
    about_privacy_h: "حریم خصوصی",
    about_privacy_body:
      "برای دریافت کانفیگ نام، ایمیل یا شماره نمی‌خواهیم. این مرورگر با یک کوکی امضاشده شناخته می‌شود. یک اثر انگشت سبک مرورگر و یک هش نمک‌دار از محدودهٔ شبکه‌ات (نه خود IP) هم فقط برای جلوگیری از سوءاستفاده نگه داشته می‌شود، و حجم مصرفی کانفیگت شمرده می‌شود تا سقف روزانه اعمال شود.",
    about_privacy_link: "متن کامل حریم خصوصی",
    about_lead: "GozarX یک ابزار رایگان است که هر روز به همه یک کانفیگ آزمایشی می‌دهد.",
    about_body: "هدف ما ساده است: دسترسی آزاد و بی‌دردسر، بدون ثبت‌نام و بدون هزینه. تیم کوچک ما روی سرعت، پایداری و حریم خصوصی تمرکز دارد.",
    about_deflect: "شاید جوابت این‌جا باشد:",
    c_topic: "موضوع",
    c_topic_ph: "یک موضوع انتخاب کن",
    c_t1: "مشکل در اتصال",
    c_t2: "سوال دربارهٔ حجم/دعوت",
    c_t3: "گزارش باگ",
    c_t4: "پیشنهاد یا سایر",
    c_msg: "پیام",
    c_msg_ph: "مشکل یا سوالت را بنویس…",
    c_handle: "راه پاسخ",
    c_handle_opt: "(اختیاری)",
    c_handle_ph: "مثلاً ایمیل یا هر راه دلخواه برای پاسخ",
    c_send: "ارسال پیام",
    c_resp: "معمولاً کمتر از ۲۴ ساعت پاسخ می‌دهیم.",
    c_sent_t: "پیامت ارسال شد",
    c_sent_p: "ممنون! اگر راه پاسخی گذاشته باشی، به‌زودی جواب می‌دهیم.",
    c_err: "لطفاً پیام را بنویس.",
    eyebrow: "سطوح PWA و سیستم",
    lead: "سطوح فراگیر محصول: نصب وب‌اپ، اعلان‌ها، و صفحه‌های آفلاین/خطا — با همان زبان بصری، در هر دو زبان و تم.",
    inst_h: "نصب GozarX",
    ios_1: "روی آیکون هم‌رسانی بزن",
    ios_2: "«افزودن به صفحهٔ اصلی» را انتخاب کن",
    ios_3: "روی «افزودن» بزن — تمام!",
    pre_h: "اعلان‌ها را روشن کن",
    pre_d: "فقط چیزهای مهم — بی‌سر‌و‌صدا.",
    pre_1t: "کانفیگ آماده شد",
    pre_1d: "وقتی کانفیگ روزانه‌ات آماده باشد",
    pre_2t: "حجمت رو به پایان است",
    pre_2d: "پیش از تمام‌شدن حجم، خبرت می‌کنیم",
    pre_3t: "خبرها و لوکیشن‌های تازه",
    pre_3d: "گاه‌به‌گاه، بدون اسپم",
    pre_on: "روشن کن",
    pre_no: "الان نه",
    ps_bl_h: "در مرورگر مسدود شده",
    ps_bl_d: "برای دریافت اعلان باید از تنظیمات مرورگر آزادش کنی.",
    ps_bl_hint: "در کروم: روی <b>قفل کنار نشانی</b> بزن ← <b>اعلان‌ها</b> ← <code>اجازه</code>. در سافاری: <b>تنظیمات ← وب‌سایت‌ها ← اعلان‌ها</b>.",
  },
  en: {
    nav_loc: "Locations",
    nav_guides: "Guides",
    nav_faq: "FAQ",
    nav_status: "My config",
    hero_eyebrow: "Free daily config",
    hero_h1_a: "Free, fast configs —",
    hero_h1_b: "in seconds",
    hero_sub: "Grab a free trial config every day; pick your location and connect with no signup. Invite friends and your daily volume grows too.",
    hero_sub_short: "A free config every day — no signup, any location you like.",
    trust1: "No signup",
    trust2: "Free forever",
    trust3: "Fresh every {h}h",
    trust4: "{n}+ configs delivered",
    w_title: "Today's free config",
    w_sub: "Pick a location and claim",
    allowance: "{v} today",
    pick: "Choose a location",
    pick_count: "{n} locations",
    rec: "Popular",
    cta_get: "Get config",
    cta_prep: "Preparing your config…",
    reassure1: "No signup",
    reassure2: "Free",
    reassure3: "Renews every {h}h",
    antibot: "Protected against bots by an invisible check",
    ts_fail: "The security check didn't load — check your connection.",
    ts_retry: "Try again",
    succ_title: "Your config is ready",
    succ_sub: "Copy the link or open it in an app.",
    ready: "Ready",
    link_label: "Config link",
    copy: "Copy",
    copied: "Copied",
    copy_manual: "Couldn't copy — text selected, copy it manually.",
    show_qr: "QR code",
    app_hint: "Tap an app to add the config to it instantly.",
    time_left: "Time left",
    usage: "Today's usage",
    of: "of",
    remaining_vol: "Left:",
    cd_h: "hours",
    cd_m: "min",
    cd_s: "sec",
    m_title: "Want more daily volume?",
    m_invite: "Invite friends",
    m_invite_d: "per successful invite",
    m_of: "of", // invite progress: "<n> of <cap> invites"
    m_invites: "invites",
    m_pwa: "Install web app",
    m_pwa_d: "one-time, permanent",
    m_pwa_done: "Installed on this device",
    m_push: "Enable notifications",
    m_push_d: "one-time",
    m_push_done: "Notifications are on",
    how_eyebrow: "Three simple steps",
    how_title: "How it works",
    how_sub: "From landing to connected in under a minute.",
    how1_t: "Pick a location",
    how1_d: "Pick one of the locations on offer right now.",
    how2_t: "Get the config",
    how2_d: "Press the button; your config is built in seconds — with no signup.",
    how3_t: "Import into your app",
    how3_d: "Copy the link or scan the QR, then import it into the app for your device.",
    loc_eyebrow: "Locations",
    loc_title: "From any country you like",
    loc_sub: "{locs} — all free, every day.",
    loc_all: "See all locations",
    loc_go: "Get",
    loc_active: "active locations",
    loc_worldwide: "Active servers around the world for free, borderless internet.",
    // /locations index page + /l/{slug} SEO landings
    loc_page_title: "Free config locations",
    loc_page_sub: "Pick the country you want — a personal config, daily and with no signup.",
    loc_page_p1:
      "Right now GozarX offers these locations: {locs}. You choose the location for every config and can switch countries every day — free, no signup.",
    loc_page_p1_any:
      "You choose the location for every config and can switch countries every day — free, no signup.",
    loc_page_p2:
      "The right country depends on what you need: pick nearby countries for low ping, or the service's own country for region-locked apps. Guides for the most popular locations are below.",
    loc_page_grid: "All active locations",
    loc_page_guides: "Popular location guides",
    land_home: "Home",
    land_related: "Related pages",
    // homepage "articles & guides" band + the footer's article row (internal links to /l/*)
    art_eyebrow: "Articles & guides",
    art_title: "Guides and articles",
    art_sub: "How to connect with each app, and answers to common questions about free configs.",
    ft_articles: "Guides & articles",
    chg_more: "{n} more locations available",
    // rewards card (account) — daily-rewards redesign
    rw_sub: "Complete missions to get more daily volume.",
    rw_day: "Day {a} of {b}",
    rw_keep: "Keep your streak going!",
    rw_claimed: "Claimed today — tomorrow:",
    rw_day_n: "day {n}",
    rw_claim_now: "Claim today's config to keep the streak alive.",
    rw_full: "Streak complete — the bonus is live on your daily volume.",
    rw_completed: "Completed",
    rw_available: "Available",
    rw_blocked: "Blocked",
    rw_foot: "More completed missions = more daily volume.",
    rw_pwa_d: "Install the GozarX web app on this device.",
    rw_push_d: "Allow notifications in your browser.",
    rw_push_err: "Couldn't enable notifications — please try again.",
    mv_eyebrow: "More volume, free",
    mv_title: "Grow your daily volume",
    mv_sub: "Do a few simple things and multiply your daily allowance — all with no payment.",
    mv_all: "See all missions",
    mv1_t: "Invite friends",
    mv1_d: "Every friend who claims a config grows your daily volume.",
    mv2_t: "Install web app",
    mv2_d: "Install the web app on your device and get bonus volume.",
    mv3_t: "Enable notifications",
    mv3_d: "Turn on notifications to know when your config is ready.",
    mv4_t: "Daily check-in",
    mv4_d: "Visit a few days in a row and earn a streak reward.",
    app_eyebrow: "Compatible apps",
    app_title: "Connect with your favorite app",
    app_sub: "The config works in Happ, v2rayNG and Streisand. Open the guide for your app.",
    app_rec: "Recommended",
    stat1: "Configs delivered",
    stat2: "Active locations",
    stat3: "Uptime",
    faq_eyebrow: "FAQ",
    faq_title: "Got a question?",
    faq_all: "See all questions",
    trust_title: "No signup. No ad tracking.",
    trust_sub: "Claiming a config needs no account, email or phone number. Your identity is just a light token kept on this browser.",
    trust_link: "Read about privacy",
    tb1: "No email",
    tb2: "No phone",
    tb3: "No signup",
    ft_tag: "A free daily trial config for everyone — no signup, fast and simple.",
    ftc_product: "Product",
    ftc_resources: "Resources",
    ftc_legal: "Legal",
    ft_get: "Get config",
    ft_loc: "Locations",
    ft_rewards: "More volume",
    ft_status: "My config",
    ft_guides: "Setup guides",
    ft_faq: "FAQ",
    ft_about: "About",
    ft_terms: "Terms of use",
    ft_privacy: "Privacy",
    ft_contact: "Contact",
    ft_rights: "All rights reserved.", // copyright year is prepended dynamically
    ft_cta_h: "Haven't grabbed today's config yet?",
    ft_cta_d: "Free, daily and no signup — under a minute to connect.",
    ft_cta_btn: "Get a free config",
    active_title: "Your config is active",
    active_sub: "Copy it, or switch its location.",
    change_loc: "Change location",
    cd_title: "You've claimed today's config",
    cd_sub: "When the timer ends, grab a fresh one.",
    cd_next: "Next config in",
    ex_title: "Today's volume is used up",
    ex_sub: "Your config still has time — only its data ran out.",
    revive_t: "Revive this exact config",
    revive_d: "Invite just <b>one friend</b>; the moment they claim their first config, yours comes back to life <b>instantly</b> — no waiting until tomorrow.",
    invite_label: "Your invite link",
    share: "Share",
    revived: "A friend accepted your invite — your config is live again! ✨",
    empty_title: "Locations are being refreshed",
    empty_sub: "No location is ready to claim yet. Check back in a few minutes.",
    empty_link: "See the FAQ",
    err_title: "Something hiccuped",
    err_sub: "No worries — your claim is untouched. Give it one more try.",
    err_retry: "Try again",
    err_help: "Help & support",
    title: "My config",
    acc_transfer: "Transfer",
    acc_cap: "Your public id · saved on this browser",
    hist_title: "Claim history",
    set_title: "Settings",
    set_lang: "Language",
    set_theme: "Theme",
    set_theme_l: "Light",
    set_theme_d: "Dark",
    set_notif: "Notifications",
    set_notif_d: "Know when your config is ready or volume is low",
    perm_denied: "Blocked in browser",
    perm_granted: "Enabled",
    danger_t: "Reset this device's data",
    danger_d: "This browser's history, volume and invites will be erased. This can't be undone.",
    danger_btn: "Reset data",
    restore_t: "Used GozarX before?",
    restore_d: "If you made a transfer code on another device, enter it here to bring back your history and invites.",
    restore_ph: "8-character code",
    restore_btn: "Restore history",
    restore_err: "Code is wrong or expired. Please check again.",
    tm_gen_title: "Move to another device",
    tm_gen_sub: "Enter this code on the new device to transfer your history, volume and invites. The code is one-time use.",
    tm_expiry: "Expires in",
    tm_copy: "Copy code",
    rm_t: "Are you sure?",
    rm_p: "All history, volume and invites on this browser will be erased. This can't be undone.",
    rm_cancel: "Cancel",
    rm_confirm: "Yes, reset",
    reset_done: "Device data reset.",
    restored: "Your history was restored! ✨",
    revive: "If today's volume runs out, just <b>one successful invite</b> revives that same config <b>instantly</b>.",
    claim: "Claim reward",
    home: "Home",
    v_contact: "Contact",
    medium: "Medium",
    faq_sub: "Quick answers to the most common questions. If yours isn't here, ask on the contact page.",
    // /about (the contact page has its own heading now — they were one page with two URLs)
    about_eyebrow: "GozarX",
    about_title: "About us",
    about_mission_h: "Our goal",
    about_free_h: "How does it stay free?",
    about_free_body:
      "Claiming a config costs nothing and has no paid step. Every config is a trial with a set length and a set daily volume; when it ends, you claim a fresh one. More volume comes from inviting friends and the site's missions, not from paying.",
    about_privacy_h: "Privacy",
    about_privacy_body:
      "We don't ask for a name, email or phone number to claim a config. This browser is recognised by a signed cookie. A light browser fingerprint and a salted hash of your network range (not the IP itself) are kept only to prevent abuse, and your config's usage is counted so the daily cap can apply.",
    about_privacy_link: "Read the full privacy policy",
    about_lead: "GozarX is a free tool that hands everyone a trial config every day.",
    about_body: "Our goal is simple: open, hassle-free access with no signup and no cost. Our small team focuses on speed, stability and privacy.",
    about_deflect: "Your answer might be here:",
    c_topic: "Topic",
    c_topic_ph: "Choose a topic",
    c_t1: "Connection issue",
    c_t2: "Question about volume/invites",
    c_t3: "Report a bug",
    c_t4: "Suggestion or other",
    c_msg: "Message",
    c_msg_ph: "Describe your issue or question…",
    c_handle: "Reply handle",
    c_handle_opt: "(optional)",
    c_handle_ph: "e.g. an email or any way to reach you",
    c_send: "Send message",
    c_resp: "We usually reply within 24 hours.",
    c_sent_t: "Your message was sent",
    c_sent_p: "Thanks! If you left a reply handle, we'll get back to you soon.",
    c_err: "Please write a message.",
    eyebrow: "PWA & system surfaces",
    lead: "The product's cross-cutting surfaces: web-app install, notifications, and offline/error pages — same visual language, in both locales and themes.",
    inst_h: "Install GozarX",
    ios_1: "Tap the Share icon",
    ios_2: "Choose “Add to Home Screen”",
    ios_3: "Tap “Add” — done!",
    pre_h: "Turn on notifications",
    pre_d: "Only what matters — quietly.",
    pre_1t: "Config ready",
    pre_1d: "When your daily config is ready",
    pre_2t: "Volume running low",
    pre_2d: "We warn you before it runs out",
    pre_3t: "News & new locations",
    pre_3d: "Occasionally, never spam",
    pre_on: "Turn on",
    pre_no: "Not now",
    ps_bl_h: "Blocked in the browser",
    ps_bl_d: "You'll need to allow it from the browser settings to get notifications.",
    ps_bl_hint: "In Chrome: click the <b>lock next to the URL</b> → <b>Notifications</b> → <code>Allow</code>. In Safari: <b>Settings → Websites → Notifications</b>.",
  },
};
