// AUTO-GENERATED from the Phase 0-8 design artifacts' i18n dictionaries (docs/website/design).
// Verbatim design copy, keyed by the design's own flat keys (e.g. hero_h1_a, cta_get). The faithful
// rebuilt components read these; edit the design artifacts + regenerate rather than hand-editing.
import type { Locale } from "@/lib/i18n";

export const DESIGN_COPY: Record<Locale, Record<string, string>> = {
  fa: {
    nav_get: "دریافت کانفیگ",
    nav_loc: "لوکیشن‌ها",
    nav_more: "حجم بیشتر",
    nav_guides: "راهنما",
    nav_faq: "سوالات",
    nav_blog: "وبلاگ",
    nav_status: "حساب کاربری",
    banner_txt: "این سایت به انگلیسی هم موجود است.",
    banner_cta: "View in English",
    pf_desktop: "دسکتاپ",
    dev_pf: "پیش‌نمایش پلتفرم:",
    hero_eyebrow: "کانفیگ رایگان روزانه",
    hero_h1_a: "کانفیگ رایگان و پرسرعت،",
    hero_h1_b: "در چند ثانیه",
    hero_sub: "هر روز یک کانفیگ آزمایشی رایگان بگیر؛ لوکیشن دلخواهت را انتخاب کن و بدون ثبت‌نام وصل شو. با دعوت دوستان هم حجم روزانه‌ات بیشتر می‌شود.",
    trust1: "بدون ثبت‌نام",
    trust2: "همیشه رایگان",
    trust3: "هر ۲۴ ساعت تازه",
    trust4: "+۱۲٬۰۰۰ کاربر",
    w_title: "کانفیگ رایگان امروز",
    w_sub: "یک لوکیشن انتخاب کن و بگیر",
    allowance: "{v} امروز",
    pick: "لوکیشن را انتخاب کن",
    pick_count: "{n} لوکیشن",
    rec: "محبوب",
    cta_get: "دریافت کانفیگ",
    cta_prep: "در حال آماده‌سازی کانفیگ…",
    reassure1: "بدون ثبت‌نام",
    reassure2: "رایگان",
    reassure3: "هر {h} ساعت تازه",
    antibot: "با یک بررسی نامرئی در برابر ربات محافظت می‌شود",
    succ_title: "کانفیگ آماده است",
    succ_sub: "لینک را کپی کن یا در اپ باز کن.",
    ready: "آماده",
    link_label: "لینک کانفیگ",
    copy: "کپی",
    copied: "کپی شد",
    show_qr: "کد QR",
    open_in: "باز کردن در اپ",
    open_ios: "برای آیفون شما",
    open_android: "برای اندروید شما",
    app_hint: "برای افزودن سریع کانفیگ روی برنامه مد نظر کلیک کنید.",
    time_left: "زمان باقی‌مانده",
    usage: "مصرف امروز",
    of: "از",
    remaining_vol: "مانده:",
    cd_h: "ساعت",
    cd_m: "دقیقه",
    cd_s: "ثانیه",
    m_title: "حجم بیشتری می‌خواهی؟",
    m_invite: "دعوت دوستان",
    m_invite_d: "به‌ازای هر دعوت موفق",
    m_of: "از", // invite progress: "<n> از <cap> دعوت"
    m_invites: "دعوت",
    m_pwa: "نصب وب‌اپ",
    m_pwa_d: "یک‌بار، همیشگی",
    m_pwa_done: "نصب‌شده روی این دستگاه",
    m_push: "روشن‌کردن اعلان‌ها",
    m_push_d: "یک‌بار",
    m_push_done: "اعلان‌ها روشن است",
    how_eyebrow: "سه قدم ساده",
    how_title: "چطور کار می‌کند؟",
    how_sub: "از ورود تا اتصال، کمتر از یک دقیقه.",
    how1_t: "لوکیشن را انتخاب کن",
    how1_d: "از میان کشورهای موجود، لوکیشن دلخواهت را بزن. همه آنلاین و آماده‌اند.",
    how2_t: "کانفیگ را بگیر",
    how2_d: "دکمهٔ دریافت را بزن؛ کانفیگ در چند ثانیه ساخته می‌شود — بدون ثبت‌نام.",
    how3_t: "در اپ وارد کن",
    how3_d: "لینک را کپی کن یا QR را اسکن کن و در اپ مخصوص دستگاهت وارد شو.",
    loc_eyebrow: "لوکیشن‌ها",
    loc_title: "از هر کشوری که بخواهی",
    loc_sub: "کانفیگ اوکراین، آلمان، آمریکا و بیشتر — همه رایگان و روزانه.",
    loc_all: "مشاهدهٔ همهٔ لوکیشن‌ها",
    loc_go: "دریافت",
    loc_active: "لوکیشن فعال",
    loc_worldwide: "سرورهای فعال در نقاط مختلف جهان برای اینترنت آزاد و بدون مرز.",
    // /locations index page + /l/{slug} SEO landings
    loc_page_title: "لوکیشن‌های کانفیگ رایگان",
    loc_page_sub: "سرور کشور دلخواهت را انتخاب کن — کانفیگ اختصاصی، روزانه و بدون ثبت‌نام.",
    loc_page_p1:
      "گذرایکس در ده‌ها کشور دنیا سرور فعال دارد؛ از آلمان و آمریکا تا ترکیه و امارات. برای هر کانفیگ، خودت لوکیشن را انتخاب می‌کنی و هر روز می‌توانی کشور را عوض کنی — بدون هزینه و بدون ثبت‌نام.",
    loc_page_p2:
      "انتخاب کشور به نیازت بستگی دارد: برای پینگ پایین سراغ کشورهای نزدیک برو و برای دسترسی به سرویس‌های خاص، کشور همان سرویس را انتخاب کن. راهنمای بعضی از پرطرفدارترین لوکیشن‌ها را در ادامه ببین.",
    loc_page_grid: "همهٔ لوکیشن‌های فعال",
    loc_page_guides: "راهنمای لوکیشن‌های پرطرفدار",
    land_home: "خانه",
    land_related: "صفحات مرتبط",
    chg_more: "{n} لوکیشن دیگر در دسترس",
    mv_eyebrow: "حجم بیشتر، رایگان",
    mv_title: "حجم روزانه‌ات را بیشتر کن",
    mv_sub: "چند کار ساده انجام بده و حجم روزانه‌ات را چند برابر کن — همه بدون پرداخت.",
    mv_all: "مشاهدهٔ همهٔ ماموریت‌ها",
    mv1_t: "دعوت دوستان",
    mv1_d: "به‌ازای هر دوست که کانفیگ بگیرد، حجم روزانه‌ات بیشتر می‌شود.",
    mv2_t: "نصب وب‌اپ",
    mv2_d: "وب‌اپ را روی دستگاهت نصب کن و حجم هدیه بگیر.",
    mv3_t: "روشن‌کردن اعلان‌ها",
    mv3_d: "اعلان‌ها را فعال کن تا از کانفیگ آماده باخبر شوی.",
    mv4_t: "ورود روزانه",
    mv4_d: "چند روز پیاپی سر بزن و پاداش استریک بگیر.",
    mv_streak: "حجم استریک",
    app_eyebrow: "اپ‌های سازگار",
    app_title: "در اپ دلخواهت باز کن",
    app_sub: "کانفیگ با همهٔ کلاینت‌های محبوب کار می‌کند. اپِ متناسب با دستگاهت را انتخاب کن.",
    app_rec: "پیشنهادی",
    app_guide: "راهنمای اتصال",
    stat1: "کانفیگ تحویل‌شده",
    stat2: "لوکیشن فعال",
    stat3: "آپ‌تایم",
    faq_eyebrow: "سوالات متداول",
    faq_title: "سوالی داری؟",
    faq_all: "مشاهدهٔ همهٔ سوالات",
    faq1_q: "کانفیگ رایگان واقعاً رایگان است؟",
    faq1_a: "بله. هر ۲۴ ساعت یک کانفیگ با حجم مشخص می‌گیری؛ نه ثبت‌نامی لازم است نه پرداختی.",
    faq2_q: "برای دریافت باید حساب بسازم؟",
    faq2_a: "نه. دریافت کاملاً بدون ثبت‌نام است؛ فقط با شناسهٔ دستگاهت کار می‌کند و هیچ ایمیل یا شماره‌ای نمی‌خواهد.",
    faq3_q: "اگر حجم امروزم تمام شود چه؟",
    faq3_a: "با یک دعوت موفق، همان کانفیگ همان لحظه دوباره فعال می‌شود — لازم نیست تا فردا صبر کنی.",
    faq4_q: "روی چه دستگاه‌هایی کار می‌کند؟",
    faq4_a: "اندروید، آیفون، ویندوز، مک و لینوکس — با اپ‌های v2rayNG، Streisand و Happ.",
    faq5_q: "چطور حجم روزانه‌ام را بیشتر کنم؟",
    faq5_a: "از بخش «حجم بیشتر» دوستانت را دعوت کن، وب‌اپ را نصب کن یا اعلان‌ها را روشن کن.",
    trust_title: "بدون ثبت‌نام. بدون ردگیری.",
    trust_sub: "برای دریافت کانفیگ هیچ حساب، ایمیل یا شماره‌ای لازم نیست. هویت فقط با یک شناسهٔ سبک روی همین مرورگر ساخته می‌شود.",
    trust_link: "دربارهٔ حریم خصوصی بخوان",
    tb1: "بدون ایمیل",
    tb2: "بدون شماره",
    tb3: "بدون ثبت‌نام",
    blog_eyebrow: "وبلاگ",
    blog_title: "آموزش‌ها و راهنماها",
    blog1_t: "آموزش کامل اتصال با v2rayNG در اندروید",
    blog1_g: "آموزش",
    blog1_r: "۵ دقیقه",
    blog2_t: "کانفیگ برای آیفون: نصب و اتصال با Streisand",
    blog2_g: "iOS",
    blog2_r: "۴ دقیقه",
    blog3_t: "فرق VLESS و VMess چیست و کدام بهتر است؟",
    blog3_g: "مفاهیم",
    blog3_r: "۶ دقیقه",
    ft_tag: "کانفیگ آزمایشی رایگان روزانه، برای همه — بدون ثبت‌نام، سریع و ساده.",
    ftc_product: "محصول",
    ftc_resources: "منابع",
    ftc_legal: "قانونی",
    ft_get: "دریافت کانفیگ",
    ft_loc: "لوکیشن‌ها",
    ft_rewards: "حجم بیشتر",
    ft_status: "حساب کاربری",
    ft_guides: "راهنمای اتصال",
    ft_faq: "سوالات متداول",
    ft_blog: "وبلاگ",
    ft_about: "دربارهٔ ما",
    ft_terms: "قوانین استفاده",
    ft_privacy: "حریم خصوصی",
    ft_contact: "تماس با ما",
    ft_copy: "© ۱۴۰۴ GozarX — همهٔ حقوق محفوظ است.",
    ft_rights: "همهٔ حقوق محفوظ است.", // copyright year is prepended dynamically
    ft_cta_h: "هنوز کانفیگ امروزت را نگرفته‌ای؟",
    ft_cta_d: "رایگان، روزانه و بدون ثبت‌نام — کمتر از یک دقیقه تا اتصال.",
    ft_cta_btn: "دریافت کانفیگ رایگان",
    units_gb: "{n} گیگابایت",
    units_mb: "{n} مگابایت",
    toast_demo: "این فقط پیش‌نمایش است.",
    tb_sub: "ویجت دریافت · فاز ۱",
    tb_light: "روشن",
    tb_dark: "تاریک",
    hero_title: "کانفیگ رایگان امروزت را در چند ثانیه بگیر",
    active_title: "کانفیگ شما فعال است",
    active_sub: "می‌توانی کپی کنی یا لوکیشن را عوض کنی.",
    change_loc: "تغییر لوکیشن",
    cd_title: "کانفیگ امروزت را گرفتی",
    cd_sub: "به‌محض پایان شمارش، کانفیگ تازه بگیر.",
    cd_next: "کانفیگ بعدی تا",
    ex_title: "حجم امروزت تمام شد",
    ex_sub: "زمان کانفیگ باقی است، فقط حجمش تمام شده.",
    revive_t: "همین کانفیگ را زنده کن",
    revive_d: "فقط <b>یک دوست</b> را دعوت کن؛ به‌محض اینکه اولین کانفیگش را بگیرد، همین کانفیگ تو <b>همان لحظه</b> دوباره فعال می‌شود — بدون صبرکردن تا فردا.",
    invite_label: "لینک دعوت تو",
    share: "اشتراک‌گذاری",
    revive_demo: "شبیه‌سازی دعوت موفق",
    revived: "یک دوست دعوتت را پذیرفت — کانفیگ دوباره فعال شد! ✨",
    empty_title: "لوکیشن‌ها در حال به‌روزرسانی‌اند",
    empty_sub: "هنوز لوکیشنی آماده نیست. چند دقیقهٔ دیگر دوباره سر بزن.",
    empty_link: "مشاهدهٔ سوالات متداول",
    err_title: "یک وقفهٔ کوتاه پیش آمد",
    err_sub: "نگران نباش، دریافت تو دست‌نخورده مانده. یک‌بار دیگر تلاش کن.",
    err_retry: "تلاش دوباره",
    err_help: "راهنما و پشتیبانی",
    gal_title: "همهٔ حالت‌های ویجت",
    gal_lede: "ویجت دریافت باید هر پاسخ بک‌اند را طراحی‌شده داشته باشد. این‌ها هشت حالت واقعی سرویس‌اند؛ کد فنی هر کدام کنار عنوانش آمده تا مستقیم به سرویس trial نگاشت شود.",
    gal_note: "هیچ عددی هاردکد نیست — حجم روزانه، ساعت تمدید و جایزهٔ دعوت همه از تنظیمات پنل می‌آیند و این‌جا فقط نمونه‌اند. پرچم‌ها هم واقعی‌اند و از ایموجیِ ریمارک هر کانفیگ استخراج می‌شوند، نه ایموجی.",
    g1: "حالت اولیه (اولین بازدید)",
    g2: "در حال آماده‌سازی",
    g3: "دریافت موفق",
    g4: "کانفیگ فعال (بازگشت کاربر)",
    g5: "کول‌داون (امروز گرفته)",
    g6: "حجم تمام‌شده + زنده‌سازی",
    g7: "بدون لوکیشن / آماده‌نبودن",
    g8: "خطای موقت پنل",
    cmp_title: "واریانت فشرده (برای لندینگ‌های سئو)",
    cmp_desc: "روی لندینگ‌های کلیدواژه‌ای، ویجت با لوکیشن پیش‌انتخاب و هدر کوتاه‌تر می‌نشیند تا کاربر بدون کلیک اضافه مستقیم دریافت کند.",
    cmp_title2: "کانفیگ رایگان اوکراین",
    cmp_sub: "لوکیشن اوکراین از قبل انتخاب شده",
    foot: "GozarX · فاز ۱ ویجت دریافت (نسخهٔ ۲) · پرچم‌های واقعی، فونت یکان‌بخ + Inter. برای بازبینی و تأیید.",
    toast_share: "پنجرهٔ اشتراک‌گذاری سیستم باز می‌شود (در نسخهٔ واقعی).",
    dev_view: "پیش‌نمایش:",
    v_dash: "داشبورد",
    v_new: "دستگاه نو",
    title: "حساب کاربری",
    idnote: "سوابق تو روی همین مرورگر ذخیره می‌شود.",
    idnote_link: "انتقال به دستگاه دیگر",
    acc_id: "شناسهٔ حساب",
    acc_id_hint: "شناسهٔ عمومی تو — برای دعوت دوستان و انتقال به دستگاه دیگر.",
    acc_transfer: "انتقال",
    acc_cap: "شناسهٔ عمومی تو · روی این مرورگر ذخیره می‌شود",
    mb_unit: "مگابایت",
    rw_installed: "نصب‌شده",
    streak_title: "استریک دریافت روزانه",
    streak_sub: "هر روز کانفیگ بگیر تا استریکت بالا برود.",
    streak_today: "امروز گرفتی",
    streak_active_note: "استریک فعال — پاداش روزانه‌ات اضافه شد.",
    st_usage: "مصرف امروز",
    st_left: "زمان باقی‌مانده",
    st_alw: "حجم روزانه",
    st_inv: "دعوت‌های موفق",
    cfg_title: "کانفیگ فعال",
    cfg_active: "فعال",
    cfg_online: "آنلاین",
    hist_title: "تاریخچهٔ دریافت",
    hist_all: "همه",
    h_ok: "فعال",
    h_exp: "منقضی",
    msum_t: "حجم بیشتری می‌خواهی؟",
    msum_d: "با دعوت دوستان و چند کار ساده حجم روزانه‌ات را بیشتر کن.",
    msum_btn: "حجم بیشتر",
    set_title: "تنظیمات",
    set_lang: "زبان",
    set_theme: "تم",
    set_theme_l: "روشن",
    set_theme_d: "تاریک",
    set_notif: "اعلان‌ها",
    set_notif_d: "از آماده‌شدن کانفیگ و کم‌شدن حجم باخبر شو",
    perm_denied: "مسدود در مرورگر",
    perm_granted: "فعال",
    danger_t: "پاک‌کردن دادهٔ این دستگاه",
    danger_d: "سوابق، حجم و دعوت‌های این مرورگر پاک می‌شود. برگشت‌پذیر نیست.",
    danger_btn: "پاک‌کردن داده",
    new_t: "هنوز کانفیگی نگرفته‌ای",
    new_d: "روی این دستگاه هنوز سابقه‌ای نیست. اولین کانفیگ رایگانت را بگیر تا وضعیتت این‌جا نشان داده شود.",
    new_get: "دریافت اولین کانفیگ",
    restore_t: "قبلاً از GozarX استفاده کرده‌ای؟",
    restore_d: "اگر روی دستگاه دیگری کد انتقال ساخته‌ای، این‌جا واردش کن تا سوابق و دعوت‌هایت برگردد.",
    restore_ph: "کد ۸ کاراکتری",
    restore_btn: "بازیابی سوابق",
    restore_err: "کد نادرست یا منقضی است. دوباره بررسی کن.",
    tm_gen_title: "انتقال به دستگاه دیگر",
    tm_gen_sub: "این کد را روی دستگاه جدید وارد کن تا سوابق، حجم و دعوت‌هایت منتقل شود. کد یک‌بارمصرف است.",
    tm_expiry: "انقضا تا",
    tm_copy: "کپی کد",
    tm_sim1: "شبیه‌سازی: وارد شد",
    tm_sim2: "شبیه‌سازی: انقضا",
    tm_simnote: "(دکمه‌های بالا فقط برای پیش‌نمایش حالت‌ها هستند)",
    tm_ok_t: "سوابقت منتقل شد!",
    tm_ok_p: "دستگاه جدید حالا به همین حساب دستگاهی وصل است.",
    tm_ok_btn: "باشه",
    tm_exp_t: "کد منقضی شد",
    tm_exp_p: "مهلت ۱۰ دقیقه‌ای این کد تمام شد. یک کد تازه بساز.",
    tm_regen: "ساخت کد جدید",
    rm_t: "مطمئنی؟",
    rm_p: "همهٔ سوابق، حجم و دعوت‌های این مرورگر پاک می‌شود. این کار برگشت‌پذیر نیست.",
    rm_cancel: "انصراف",
    rm_confirm: "بله، پاک کن",
    reset_done: "دادهٔ دستگاه پاک شد.",
    restored: "سوابقت بازیابی شد! ✨",
    p_eyebrow: "حجم بیشتر، رایگان",
    p_title: "حجم روزانه‌ات را بیشتر کن",
    p_sub: "با چند کار ساده و رایگان، حجم روزانه‌ات را چند برابر کن. همه‌چیز روی همین دستگاه ذخیره می‌شود.",
    per_day: "در روز",
    bd_title: "حجم روزانهٔ فعلی شما",
    bd_sub: "از مجموع پایه و پاداش‌هایی که تا حالا گرفته‌ای:",
    lg_base: "حجم پایه",
    lg_inv: "دعوت دوستان",
    lg_mis: "ماموریت‌ها",
    inv_title: "دعوت دوستان",
    inv_sub: "قوی‌ترین راه برای بیشترکردن حجم",
    inv_reward: "{v} به‌ازای هر نفر",
    inv_link_label: "لینک دعوت اختصاصی تو",
    inv_copy: "کپی",
    inv_copied: "کپی شد",
    inv_share: "اشتراک‌گذاری لینک",
    inv_prog: "دعوت‌های موفق",
    revive: "اگر حجم امروزت تمام شود، فقط <b>یک دعوت موفق</b> کافی است تا همان کانفیگ <b>همان لحظه</b> دوباره زنده شود.",
    ms_title: "ماموریت‌ها",
    ms_sub: "هر ماموریت را یک‌بار انجام بده و پاداشش را بگیر.",
    m_pwa_t: "نصب وب‌اپ",
    m_pwa_btn: "نصب و دریافت پاداش",
    m_push_t: "روشن‌کردن اعلان‌ها",
    m_push_btn: "فعال‌سازی اعلان‌ها",
    m_streak_t: "ورود روزانه",
    m_streak_d: "چند روز پیاپی سر بزن و بعد از {d} روز پاداش استریک بگیر.",
    m_streak_cap: "{a} از {d} روز — فردا هم سر بزن!",
    st_done: "دریافت شد",
    st_prog: "در حال انجام",
    st_unav: "در این دستگاه نیست",
    claim: "دریافت پاداش",
    ref_title: "حالت‌های کارت ماموریت",
    ref_note: "هر کارت ماموریت بسته به وضعیت کاربر یکی از این حالت‌ها را دارد:",
    ref_avail_t: "قابل دریافت",
    ref_avail_d: "ماموریت آماده است؛ انجامش بده و پاداش بگیر.",
    ref_prog_t: "در حال انجام",
    ref_prog_d: "شروع کرده‌ای ولی هنوز کامل نشده (مثل استریک).",
    ref_done_t: "دریافت‌شده",
    ref_done_d: "پاداش این ماموریت قبلاً به حجمت اضافه شده.",
    ref_unav_t: "غیرقابل‌انجام",
    ref_unav_d: "روی این دستگاه/مرورگر ممکن نیست.",
    ref_unav_why: "این مرورگر روی iOS از اعلان وب پشتیبانی کامل ندارد. برای اعلان، وب‌اپ را نصب کن.",
    done_toast: "{v} به حجم روزانه‌ات اضافه شد!",
    share_toast: "پنجرهٔ اشتراک‌گذاری سیستم باز می‌شود (در نسخهٔ واقعی).",
    fp_title: "قوانین و نکات",
    fp1: "هر ماموریت یک‌بار و برای هر دستگاه قابل‌دریافت است.",
    fp2: "پاداش‌ها به حجم روزانه اضافه می‌شوند، نه یک‌بار مصرف.",
    fp3: "استفادهٔ غیرمنصفانه (چند حساب/ربات) باعث لغو پاداش می‌شود.",
    fp4: "مقادیر پاداش از تنظیمات پنل می‌آیند و ممکن است تغییر کنند.",
    unit_gb: "گیگابایت",
    unit_mb: "مگابایت",
    home: "خانه",
    v_guides: "راهنماها",
    v_guide: "راهنمای اندروید",
    v_faq: "سوالات",
    v_blog: "وبلاگ",
    v_post: "مقاله",
    v_contact: "تماس",
    v_legal: "قوانین",
    read_more: "ادامه",
    easy: "آسان",
    medium: "متوسط",
    g_title: "راهنمای اتصال",
    g_sub: "سیستم‌عاملت را انتخاب کن و قدم‌به‌قدم وصل شو. همه راهنماها کوتاه و ساده‌اند.",
    g_apps: "اپ‌ها:",
    g_time: "~۳ دقیقه",
    g_view: "مشاهدهٔ راهنما",
    gd_time: "زمان: ~۳ دقیقه",
    gd_toc: "فهرست مطالب",
    gd_help_q: "این راهنما مفید بود؟",
    gd_yes: "بله",
    gd_no: "نه",
    gd_thanks: "ممنون از بازخوردت!",
    gd_trouble: "عیب‌یابی",
    gd_prev: "قبلی",
    gd_next: "بعدی",
    faq_sub: "پاسخ سریع به پرتکرارترین سوال‌ها. اگر جوابت این‌جا نبود، از صفحهٔ تماس بپرس.",
    faq_search: "جستجو در سوالات…",
    faq_empty: "سوالی با این عبارت پیدا نشد.",
    cat_all: "همه",
    cat_start: "شروع",
    cat_vol: "حجم و دعوت",
    cat_apps: "اپ‌ها",
    cat_trouble: "عیب‌یابی",
    blog_sub: "آموزش‌ها، مفاهیم و اخبار GozarX.",
    blog_all: "همه",
    read: "مطالعه",
    post_by: "تیم GozarX",
    cta_h: "همین حالا کانفیگ رایگانت را بگیر",
    cta_p: "یک لوکیشن انتخاب کن و در چند ثانیه وصل شو — بدون ثبت‌نام.",
    cta_btn: "دریافت کانفیگ",
    related: "مقالات مرتبط",
    about_title: "دربارهٔ ما و تماس",
    about_lead: "GozarX یک ابزار رایگان است که هر روز به همه یک کانفیگ آزمایشی می‌دهد.",
    about_body: "هدف ما ساده است: دسترسی آزاد و بی‌دردسر، بدون ثبت‌نام و بدون هزینه. تیم کوچک ما روی سرعت، پایداری و حریم خصوصی تمرکز دارد.",
    about_deflect: "شاید جوابت این‌جا باشد:",
    c_topic: "موضوع",
    c_topic_ph: "یک موضوع انتخاب کن",
    c_t1: "مشکل در اتصال",
    c_t2: "سوال دربارهٔ حجم/دعوت",
    c_t3: "گزارش باگ",
    c_t4: "پیشنهاد یا سایر",
    c_msg: "پیام",
    c_msg_ph: "مشکل یا سوالت را بنویس…",
    c_handle: "راه پاسخ",
    c_handle_opt: "(اختیاری)",
    c_handle_ph: "مثلاً ایمیل یا هر راه دلخواه برای پاسخ",
    c_send: "ارسال پیام",
    c_resp: "معمولاً کمتر از ۲۴ ساعت پاسخ می‌دهیم.",
    c_sent_t: "پیامت ارسال شد",
    c_sent_p: "ممنون! اگر راه پاسخی گذاشته باشی، به‌زودی جواب می‌دهیم.",
    c_err: "لطفاً پیام را بنویس.",
    legal_terms: "قوانین استفاده",
    legal_privacy: "حریم خصوصی",
    legal_updated: "آخرین به‌روزرسانی: تیر ۱۴۰۴",
    dev_hint: "فاز ۷ — همه‌چیز در فارسی/انگلیسی × روشن/تاریک قابل بازبینی است",
    eyebrow: "سطوح PWA و سیستم",
    lead: "سطوح فراگیر محصول: نصب وب‌اپ، اعلان‌ها، و صفحه‌های آفلاین/خطا — با همان زبان بصری، در هر دو زبان و تم.",
    sn_pwa: "نصب اپ",
    sn_push: "اعلان‌ها",
    sn_offline: "آفلاین",
    sn_err: "خطاها",
    sn_load: "بارگذاری و توست",
    pwa_h: "نصب وب‌اپ (PWA)",
    pwa_d: "روی اندروید/دسکتاپ یک شیت قابل‌رد‌شدن، روی iOS راهنمای دستی، و حالت «نصب شد».",
    cap_android: "اندروید / دسکتاپ — شیت نرم",
    cap_ios: "iOS سافاری — مراحل دستی",
    cap_installed: "حالت نصب‌شده",
    inst_h: "نصب GozarX",
    inst_d: "سریع‌تر باز می‌شود، تمام‌صفحه و بدون نوار مرورگر.",
    inst_btn: "نصب",
    inst_later: "بعداً",
    inst_live: "نمایش زنده",
    ios_1: "روی آیکون هم‌رسانی بزن",
    ios_2: "«افزودن به صفحهٔ اصلی» را انتخاب کن",
    ios_3: "روی «افزودن» بزن — تمام!",
    ios_share: "هم‌رسانی",
    ios_add: "افزودن به صفحهٔ اصلی",
    installed_h: "GozarX روی دستگاهت نصب شد",
    installed_d: "حالا از صفحهٔ اصلی، تمام‌صفحه بازش کن.",
    installed_open: "باز کردن اپ",
    push_h: "اعلان‌ها",
    push_d: "قبل از پرامپت مرورگر توضیح می‌دهیم چه می‌فرستیم، بعد حالت‌های فعال/رد/مسدود.",
    cap_pre: "شیت توضیح پیش از مجوز",
    cap_states: "حالت‌های مجوز",
    pre_h: "اعلان‌ها را روشن کن",
    pre_d: "فقط چیزهای مهم — بی‌سر‌و‌صدا.",
    pre_1t: "کانفیگ آماده شد",
    pre_1d: "وقتی کانفیگ روزانه‌ات آماده باشد",
    pre_2t: "حجمت رو به پایان است",
    pre_2d: "پیش از تمام‌شدن حجم، خبرت می‌کنیم",
    pre_3t: "خبرها و لوکیشن‌های تازه",
    pre_3d: "گاه‌به‌گاه، بدون اسپم",
    pre_on: "روشن کن",
    pre_no: "الان نه",
    pre_live: "نمایش زنده",
    ps_ok_h: "اعلان‌ها فعال است",
    ps_ok_d: "هر وقت بخواهی از تنظیمات خاموشش کن.",
    ps_ok_tag: "فعال",
    ps_no_h: "الان نه",
    ps_no_d: "هر وقت آماده بودی از تنظیمات روشنش کن.",
    ps_no_tag: "رد شد",
    ps_bl_h: "در مرورگر مسدود شده",
    ps_bl_d: "برای دریافت اعلان باید از تنظیمات مرورگر آزادش کنی.",
    ps_bl_tag: "مسدود",
    ps_bl_hint: "در کروم: روی <b>قفل کنار نشانی</b> بزن ← <b>اعلان‌ها</b> ← <code>اجازه</code>. در سافاری: <b>تنظیمات ← وب‌سایت‌ها ← اعلان‌ها</b>.",
    off_h: "صفحهٔ آفلاین",
    off_d: "وقتی اینترنت قطع است، دوستانه و کاربردی — با آخرین کانفیگ کش‌شده.",
    off_code: "آفلاین",
    off_t: "اتصال اینترنت نیست",
    off_dd: "به نظر می‌رسد آفلاین هستی. آخرین کانفیگت این‌جاست تا همان را وصل کنی.",
    off_cached: "آخرین کانفیگ کش‌شده",
    off_retry: "تلاش دوباره",
    err_h: "۴۰۴ و ۵۰۰ / تعمیرات",
    err_d: "۴۰۴ بازیگوش با جستجو و لینک‌ها؛ ۵۰۰ آرام با تلاش دوباره و لینک سوالات — بدون لینک وضعیت بیرونی.",
    cap_404: "۴۰۴ — پیدا نشد",
    cap_500: "۵۰۰ / تعمیرات",
    e404_code: "خطای ۴۰۴",
    e404_t: "این صفحه پیدا نشد",
    e404_d: "شاید نشانی عوض شده یا صفحه برداشته شده. بیا برگردیم به مسیر.",
    e404_search: "چیزی جستجو کن…",
    e404_go: "جستجو",
    e404_links: "صفحه‌های پرطرفدار:",
    e500_code: "خطای ۵۰۰",
    e500_t: "یک لحظه… مشکلی پیش آمد",
    e500_d: "از سمت ما بود، نه تو. داریم درستش می‌کنیم — چند لحظه بعد دوباره امتحان کن.",
    e500_retry: "تلاش دوباره",
    e500_faq: "سوالات متداول",
    maint_note: "حالت تعمیرات همین صفحه است با متن آرام‌تر؛ هیچ لینک وضعیت بیرونی نمی‌گذاریم.",
    load_h: "اسکلت‌های بارگذاری و توست‌ها",
    load_d: "اسکلت‌های سراسری (هیرو و وضعیت)، جای پشتهٔ توست، و توست به‌روزرسانی اپ.",
    cap_skel_hero: "اسکلت هیرو صفحهٔ اصلی",
    cap_skel_status: "اسکلت صفحهٔ وضعیت",
    cap_toast: "پشتهٔ توست",
    toast_update_b: "نسخهٔ جدید آماده است",
    toast_update_s: "برای دریافت آخرین نسخه تازه‌سازی کن.",
    toast_refresh: "تازه‌سازی",
    toast_success: "کپی شد ✓",
    toast_upd_demo: "نمایش توست به‌روزرسانی",
    toast_note: "جای توست‌ها: بالا و در لبهٔ پایانی (<b>top / inline-end</b>) — با ویژگی‌های منطقی CSS. در فارسی بالا-چپ و در انگلیسی بالا-راست؛ زیر هدر چسبان و در سمت مقابلِ لوگو، تا مسیر خواندن و ناوبری اصلی را نپوشاند.",
    mb: "{n} مگابایت",
  },
  en: {
    nav_get: "Get config",
    nav_loc: "Locations",
    nav_more: "More volume",
    nav_guides: "Guides",
    nav_faq: "FAQ",
    nav_blog: "Blog",
    nav_status: "Account",
    banner_txt: "This page is also available in Persian.",
    banner_cta: "نمایش به فارسی",
    pf_desktop: "Desktop",
    dev_pf: "Platform preview:",
    hero_eyebrow: "Free daily config",
    hero_h1_a: "Free, fast configs —",
    hero_h1_b: "in seconds",
    hero_sub: "Grab a free trial config every day; pick your location and connect with no signup. Invite friends and your daily volume grows too.",
    trust1: "No signup",
    trust2: "Free forever",
    trust3: "Fresh every 24h",
    trust4: "12,000+ users",
    w_title: "Today's free config",
    w_sub: "Pick a location and claim",
    allowance: "{v} today",
    pick: "Choose a location",
    pick_count: "{n} locations",
    rec: "Popular",
    cta_get: "Get config",
    cta_prep: "Preparing your config…",
    reassure1: "No signup",
    reassure2: "Free",
    reassure3: "Renews every {h}h",
    antibot: "Protected against bots by an invisible check",
    succ_title: "Your config is ready",
    succ_sub: "Copy the link or open it in an app.",
    ready: "Ready",
    link_label: "Config link",
    copy: "Copy",
    copied: "Copied",
    show_qr: "QR code",
    open_in: "Open in app",
    open_ios: "For your iPhone",
    open_android: "For your Android",
    app_hint: "Tap an app to add the config to it instantly.",
    time_left: "Time left",
    usage: "Today's usage",
    of: "of",
    remaining_vol: "Left:",
    cd_h: "hours",
    cd_m: "min",
    cd_s: "sec",
    m_title: "Want more daily volume?",
    m_invite: "Invite friends",
    m_invite_d: "per successful invite",
    m_of: "of", // invite progress: "<n> of <cap> invites"
    m_invites: "invites",
    m_pwa: "Install web app",
    m_pwa_d: "one-time, permanent",
    m_pwa_done: "Installed on this device",
    m_push: "Enable notifications",
    m_push_d: "one-time",
    m_push_done: "Notifications are on",
    how_eyebrow: "Three simple steps",
    how_title: "How it works",
    how_sub: "From landing to connected in under a minute.",
    how1_t: "Pick a location",
    how1_d: "Choose your country from the available list — all online and ready to go.",
    how2_t: "Get the config",
    how2_d: "Press the button; your config is built in seconds — with no signup.",
    how3_t: "Import into your app",
    how3_d: "Copy the link or scan the QR, then import it into the app for your device.",
    loc_eyebrow: "Locations",
    loc_title: "From any country you like",
    loc_sub: "Ukraine, Germany, USA and more — all free, every day.",
    loc_all: "See all locations",
    loc_go: "Get",
    loc_active: "active locations",
    loc_worldwide: "Active servers around the world for free, borderless internet.",
    // /locations index page + /l/{slug} SEO landings
    loc_page_title: "Free config locations",
    loc_page_sub: "Pick the country you want — a personal config, daily and with no signup.",
    loc_page_p1:
      "GozarX runs active servers in dozens of countries, from Germany and the USA to Turkey and the UAE. You choose the location for every config and can switch countries every day — free, no signup.",
    loc_page_p2:
      "The right country depends on what you need: pick nearby countries for low ping, or the service's own country for region-locked apps. Guides for the most popular locations are below.",
    loc_page_grid: "All active locations",
    loc_page_guides: "Popular location guides",
    land_home: "Home",
    land_related: "Related pages",
    chg_more: "{n} more locations available",
    mv_eyebrow: "More volume, free",
    mv_title: "Grow your daily volume",
    mv_sub: "Do a few simple things and multiply your daily allowance — all with no payment.",
    mv_all: "See all missions",
    mv1_t: "Invite friends",
    mv1_d: "Every friend who claims a config grows your daily volume.",
    mv2_t: "Install web app",
    mv2_d: "Install the web app on your device and get bonus volume.",
    mv3_t: "Enable notifications",
    mv3_d: "Turn on notifications to know when your config is ready.",
    mv4_t: "Daily check-in",
    mv4_d: "Visit a few days in a row and earn a streak reward.",
    mv_streak: "streak volume",
    app_eyebrow: "Compatible apps",
    app_title: "Open in your favorite app",
    app_sub: "Configs work with every popular client. Pick the app that fits your device.",
    app_rec: "Recommended",
    app_guide: "Setup guide",
    stat1: "Configs delivered",
    stat2: "Active locations",
    stat3: "Uptime",
    faq_eyebrow: "FAQ",
    faq_title: "Got a question?",
    faq_all: "See all questions",
    faq1_q: "Is the free config really free?",
    faq1_a: "Yes. Every 24 hours you get a config with a set volume; no signup, no payment.",
    faq2_q: "Do I need an account to claim?",
    faq2_a: "No. Claiming is entirely signup-free; it works from your device identity and needs no email or phone number.",
    faq3_q: "What if I use up today's volume?",
    faq3_a: "One successful invite revives the same config instantly — no waiting until tomorrow.",
    faq4_q: "Which devices does it work on?",
    faq4_a: "Android, iPhone, Windows, macOS and Linux — with v2rayNG, Streisand and Happ.",
    faq5_q: "How do I grow my daily volume?",
    faq5_a: "From the 'More volume' section, invite friends, install the web app, or enable notifications.",
    trust_title: "No signup. No tracking.",
    trust_sub: "Claiming a config needs no account, email or phone number. Your identity is just a light token kept on this browser.",
    trust_link: "Read about privacy",
    tb1: "No email",
    tb2: "No phone",
    tb3: "No signup",
    blog_eyebrow: "Blog",
    blog_title: "Guides & tutorials",
    blog1_t: "Full guide: connecting with v2rayNG on Android",
    blog1_g: "Guide",
    blog1_r: "5 min",
    blog2_t: "Config for iPhone: install and connect with Streisand",
    blog2_g: "iOS",
    blog2_r: "4 min",
    blog3_t: "VLESS vs VMess: what's the difference and which is better?",
    blog3_g: "Concepts",
    blog3_r: "6 min",
    ft_tag: "A free daily trial config for everyone — no signup, fast and simple.",
    ftc_product: "Product",
    ftc_resources: "Resources",
    ftc_legal: "Legal",
    ft_get: "Get config",
    ft_loc: "Locations",
    ft_rewards: "More volume",
    ft_status: "Account",
    ft_guides: "Setup guides",
    ft_faq: "FAQ",
    ft_blog: "Blog",
    ft_about: "About",
    ft_terms: "Terms of use",
    ft_privacy: "Privacy",
    ft_contact: "Contact",
    ft_copy: "© 2025 GozarX — All rights reserved.",
    ft_rights: "All rights reserved.", // copyright year is prepended dynamically
    ft_cta_h: "Haven't grabbed today's config yet?",
    ft_cta_d: "Free, daily and no signup — under a minute to connect.",
    ft_cta_btn: "Get a free config",
    units_gb: "{n} GB",
    units_mb: "{n} MB",
    toast_demo: "This is just a preview.",
    tb_sub: "Claim widget · Phase 1",
    tb_light: "Light",
    tb_dark: "Dark",
    hero_title: "Get today's free config in seconds",
    active_title: "Your config is active",
    active_sub: "Copy it, or switch its location.",
    change_loc: "Change location",
    cd_title: "You've claimed today's config",
    cd_sub: "When the timer ends, grab a fresh one.",
    cd_next: "Next config in",
    ex_title: "Today's volume is used up",
    ex_sub: "Your config still has time — only its data ran out.",
    revive_t: "Revive this exact config",
    revive_d: "Invite just <b>one friend</b>; the moment they claim their first config, yours comes back to life <b>instantly</b> — no waiting until tomorrow.",
    invite_label: "Your invite link",
    share: "Share",
    revive_demo: "Simulate a successful invite",
    revived: "A friend accepted your invite — your config is live again! ✨",
    empty_title: "Locations are being refreshed",
    empty_sub: "No location is ready to claim yet. Check back in a few minutes.",
    empty_link: "See the FAQ",
    err_title: "Something hiccuped",
    err_sub: "No worries — your claim is untouched. Give it one more try.",
    err_retry: "Try again",
    err_help: "Help & support",
    gal_title: "Every widget state",
    gal_lede: "The claim widget must design every backend response. These are the service's eight real states; each one's technical code sits by its title so it maps straight onto the trial service.",
    gal_note: "No number is hardcoded — daily volume, renewal hours and invite reward all come from panel settings; these are only samples. Flags are real too, derived from each config remark's emoji rather than rendered as emoji.",
    g1: "Idle (first visit)",
    g2: "Provisioning",
    g3: "Claimed successfully",
    g4: "Active config (returning user)",
    g5: "Cooldown (already claimed today)",
    g6: "Data exhausted + revive",
    g7: "No locations / not ready",
    g8: "Transient panel error",
    cmp_title: "Compact variant (for SEO landings)",
    cmp_desc: "On keyword landing pages the widget sits with its location pre-selected and a shorter header, so visitors claim directly with zero extra clicks.",
    cmp_title2: "Free Ukraine config",
    cmp_sub: "Ukraine is pre-selected",
    foot: "GozarX · Phase 1 claim widget (v2) · Real flags, Yekan Bakh + Inter. For review & approval.",
    toast_share: "The system share sheet opens (in the real build).",
    dev_view: "Preview:",
    v_dash: "Dashboard",
    v_new: "New device",
    title: "Account",
    idnote: "Your history lives on this browser.",
    idnote_link: "Move to another device",
    acc_id: "Account ID",
    acc_id_hint: "Your public id — for inviting friends and moving to another device.",
    acc_transfer: "Transfer",
    acc_cap: "Your public id · saved on this browser",
    mb_unit: "MB",
    rw_installed: "Installed",
    streak_title: "Daily claim streak",
    streak_sub: "Claim a config every day to grow your streak.",
    streak_today: "Claimed today",
    streak_active_note: "Streak active — your daily bonus is added.",
    st_usage: "Today's usage",
    st_left: "Time left",
    st_alw: "Daily volume",
    st_inv: "Successful invites",
    cfg_title: "Active config",
    cfg_active: "Active",
    cfg_online: "Online",
    hist_title: "Claim history",
    hist_all: "All",
    h_ok: "Active",
    h_exp: "Expired",
    msum_t: "Want more volume?",
    msum_d: "Invite friends and do a few simple things to grow your daily volume.",
    msum_btn: "More volume",
    set_title: "Settings",
    set_lang: "Language",
    set_theme: "Theme",
    set_theme_l: "Light",
    set_theme_d: "Dark",
    set_notif: "Notifications",
    set_notif_d: "Know when your config is ready or volume is low",
    perm_denied: "Blocked in browser",
    perm_granted: "Enabled",
    danger_t: "Reset this device's data",
    danger_d: "This browser's history, volume and invites will be erased. This can't be undone.",
    danger_btn: "Reset data",
    new_t: "You haven't claimed a config yet",
    new_d: "There's no history on this device yet. Get your first free config and your status will show up here.",
    new_get: "Get your first config",
    restore_t: "Used GozarX before?",
    restore_d: "If you made a transfer code on another device, enter it here to bring back your history and invites.",
    restore_ph: "8-character code",
    restore_btn: "Restore history",
    restore_err: "Code is wrong or expired. Please check again.",
    tm_gen_title: "Move to another device",
    tm_gen_sub: "Enter this code on the new device to transfer your history, volume and invites. The code is one-time use.",
    tm_expiry: "Expires in",
    tm_copy: "Copy code",
    tm_sim1: "Sim: redeemed",
    tm_sim2: "Sim: expire",
    tm_simnote: "(the buttons above only preview the states)",
    tm_ok_t: "Your history was moved!",
    tm_ok_p: "The new device is now linked to this device account.",
    tm_ok_btn: "Got it",
    tm_exp_t: "The code expired",
    tm_exp_p: "This code's 10-minute window is over. Generate a fresh one.",
    tm_regen: "Generate a new code",
    rm_t: "Are you sure?",
    rm_p: "All history, volume and invites on this browser will be erased. This can't be undone.",
    rm_cancel: "Cancel",
    rm_confirm: "Yes, reset",
    reset_done: "Device data reset.",
    restored: "Your history was restored! ✨",
    p_eyebrow: "More volume, free",
    p_title: "Grow your daily volume",
    p_sub: "Multiply your daily allowance with a few simple, free actions. Everything is stored on this device.",
    per_day: "per day",
    bd_title: "Your current daily volume",
    bd_sub: "From your base plus the rewards you've earned so far:",
    lg_base: "Base volume",
    lg_inv: "Friend invites",
    lg_mis: "Missions",
    inv_title: "Invite friends",
    inv_sub: "The strongest way to grow your volume",
    inv_reward: "{v} per friend",
    inv_link_label: "Your personal invite link",
    inv_copy: "Copy",
    inv_copied: "Copied",
    inv_share: "Share link",
    inv_prog: "Successful invites",
    revive: "If today's volume runs out, just <b>one successful invite</b> revives that same config <b>instantly</b>.",
    ms_title: "Missions",
    ms_sub: "Do each mission once and claim its reward.",
    m_pwa_t: "Install web app",
    m_pwa_btn: "Install & claim reward",
    m_push_t: "Enable notifications",
    m_push_btn: "Enable notifications",
    m_streak_t: "Daily check-in",
    m_streak_d: "Visit a few days in a row and earn a streak reward after {d} days.",
    m_streak_cap: "{a} of {d} days — come back tomorrow!",
    st_done: "Claimed",
    st_prog: "In progress",
    st_unav: "Not on this device",
    claim: "Claim reward",
    ref_title: "Mission-card states",
    ref_note: "Each mission card shows one of these states depending on the user:",
    ref_avail_t: "Available",
    ref_avail_d: "The mission is ready — do it and claim the reward.",
    ref_prog_t: "In progress",
    ref_prog_d: "You've started but not finished yet (like a streak).",
    ref_done_t: "Claimed",
    ref_done_d: "This mission's reward is already in your volume.",
    ref_unav_t: "Unavailable",
    ref_unav_d: "Not possible on this device/browser.",
    ref_unav_why: "This browser on iOS doesn't fully support web notifications. Install the web app to get them.",
    done_toast: "{v} added to your daily volume!",
    share_toast: "The system share sheet opens (in the real build).",
    fp_title: "Rules & notes",
    fp1: "Each mission can be claimed once, per device.",
    fp2: "Rewards add to your daily volume — they're not one-time.",
    fp3: "Unfair use (multiple accounts / bots) voids rewards.",
    fp4: "Reward amounts come from panel settings and may change.",
    unit_gb: "GB",
    unit_mb: "MB",
    home: "Home",
    v_guides: "Guides",
    v_guide: "Android guide",
    v_faq: "FAQ",
    v_blog: "Blog",
    v_post: "Article",
    v_contact: "Contact",
    v_legal: "Legal",
    read_more: "Read",
    easy: "Easy",
    medium: "Medium",
    g_title: "Setup guides",
    g_sub: "Pick your OS and connect step by step. Every guide is short and simple.",
    g_apps: "Apps:",
    g_time: "~3 min",
    g_view: "View guide",
    gd_time: "Time: ~3 min",
    gd_toc: "On this page",
    gd_help_q: "Was this guide helpful?",
    gd_yes: "Yes",
    gd_no: "No",
    gd_thanks: "Thanks for your feedback!",
    gd_trouble: "Troubleshooting",
    gd_prev: "Previous",
    gd_next: "Next",
    faq_sub: "Quick answers to the most common questions. If yours isn't here, ask on the contact page.",
    faq_search: "Search questions…",
    faq_empty: "No question matches that phrase.",
    cat_all: "All",
    cat_start: "Getting started",
    cat_vol: "Volume & invites",
    cat_apps: "Apps",
    cat_trouble: "Troubleshooting",
    blog_sub: "Guides, concepts and GozarX news.",
    blog_all: "All",
    read: "Read",
    post_by: "The GozarX team",
    cta_h: "Get your free config now",
    cta_p: "Pick a location and connect in seconds — no signup.",
    cta_btn: "Get config",
    related: "Related articles",
    about_title: "About & contact",
    about_lead: "GozarX is a free tool that hands everyone a trial config every day.",
    about_body: "Our goal is simple: open, hassle-free access with no signup and no cost. Our small team focuses on speed, stability and privacy.",
    about_deflect: "Your answer might be here:",
    c_topic: "Topic",
    c_topic_ph: "Choose a topic",
    c_t1: "Connection issue",
    c_t2: "Question about volume/invites",
    c_t3: "Report a bug",
    c_t4: "Suggestion or other",
    c_msg: "Message",
    c_msg_ph: "Describe your issue or question…",
    c_handle: "Reply handle",
    c_handle_opt: "(optional)",
    c_handle_ph: "e.g. an email or any way to reach you",
    c_send: "Send message",
    c_resp: "We usually reply within 24 hours.",
    c_sent_t: "Your message was sent",
    c_sent_p: "Thanks! If you left a reply handle, we'll get back to you soon.",
    c_err: "Please write a message.",
    legal_terms: "Terms of use",
    legal_privacy: "Privacy",
    legal_updated: "Last updated: July 2025",
    dev_hint: "Phase 7 — reviewable across fa/en × light/dark",
    eyebrow: "PWA & system surfaces",
    lead: "The product's cross-cutting surfaces: web-app install, notifications, and offline/error pages — same visual language, in both locales and themes.",
    sn_pwa: "Install",
    sn_push: "Notifications",
    sn_offline: "Offline",
    sn_err: "Errors",
    sn_load: "Loading & toasts",
    pwa_h: "Install the web app (PWA)",
    pwa_d: "A dismissible sheet on Android/desktop, manual steps on iOS, and the “installed” state.",
    cap_android: "Android / desktop — soft prompt",
    cap_ios: "iOS Safari — manual steps",
    cap_installed: "Installed state",
    inst_h: "Install GozarX",
    inst_d: "Opens faster, full-screen, no browser bar.",
    inst_btn: "Install",
    inst_later: "Later",
    inst_live: "Live preview",
    ios_1: "Tap the Share icon",
    ios_2: "Choose “Add to Home Screen”",
    ios_3: "Tap “Add” — done!",
    ios_share: "Share",
    ios_add: "Add to Home Screen",
    installed_h: "GozarX is installed",
    installed_d: "Now open it full-screen from your home screen.",
    installed_open: "Open app",
    push_h: "Notifications",
    push_d: "We explain what we send before the browser prompt, then granted/denied/blocked states.",
    cap_pre: "Pre-permission explainer",
    cap_states: "Permission states",
    pre_h: "Turn on notifications",
    pre_d: "Only what matters — quietly.",
    pre_1t: "Config ready",
    pre_1d: "When your daily config is ready",
    pre_2t: "Volume running low",
    pre_2d: "We warn you before it runs out",
    pre_3t: "News & new locations",
    pre_3d: "Occasionally, never spam",
    pre_on: "Turn on",
    pre_no: "Not now",
    pre_live: "Live preview",
    ps_ok_h: "Notifications on",
    ps_ok_d: "Turn it off anytime from settings.",
    ps_ok_tag: "Granted",
    ps_no_h: "Not now",
    ps_no_d: "Turn it on from settings whenever you're ready.",
    ps_no_tag: "Dismissed",
    ps_bl_h: "Blocked in the browser",
    ps_bl_d: "You'll need to allow it from the browser settings to get notifications.",
    ps_bl_tag: "Blocked",
    ps_bl_hint: "In Chrome: click the <b>lock next to the URL</b> → <b>Notifications</b> → <code>Allow</code>. In Safari: <b>Settings → Websites → Notifications</b>.",
    off_h: "Offline page",
    off_d: "When the connection drops — friendly and useful, with the last cached config.",
    off_code: "Offline",
    off_t: "No internet connection",
    off_dd: "Looks like you're offline. Your last config is right here so you can reconnect.",
    off_cached: "Last cached config",
    off_retry: "Try again",
    err_h: "404 and 500 / maintenance",
    err_d: "A playful 404 with search and links; a calm 500 with retry and a FAQ link — no external status links.",
    cap_404: "404 — Not found",
    cap_500: "500 / maintenance",
    e404_code: "Error 404",
    e404_t: "This page wasn't found",
    e404_d: "Maybe the address changed or the page moved. Let's get you back on track.",
    e404_search: "Search for something…",
    e404_go: "Search",
    e404_links: "Popular pages:",
    e500_code: "Error 500",
    e500_t: "One moment… something went wrong",
    e500_d: "That was on us, not you. We're fixing it — try again in a moment.",
    e500_retry: "Try again",
    e500_faq: "FAQ",
    maint_note: "Maintenance is this same page with a calmer tone; we never add external status links.",
    load_h: "Loading skeletons & toasts",
    load_d: "Global skeletons (hero and status), the toast-stack position, and the app-update toast.",
    cap_skel_hero: "Homepage hero skeleton",
    cap_skel_status: "Status page skeleton",
    cap_toast: "Toast stack",
    toast_update_b: "A new version is ready",
    toast_update_s: "Refresh to get the latest version.",
    toast_refresh: "Refresh",
    toast_success: "Copied ✓",
    toast_upd_demo: "Show update toast",
    toast_note: "Toast position: top, at the <b>inline-end</b> (top / inline-end) via CSS logical properties. Top-left in Persian, top-right in English; below the sticky header and opposite the logo, so it never covers the reading flow or the main nav.",
    mb: "{n} MB",
  },
};
