"""content link_preview + button_configs style

Revision ID: 43fa64c4458a
Revises: 6dc8fbdbe182
Create Date: 2026-06-28 01:27:18.947236

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "43fa64c4458a"
down_revision: str | None = "6dc8fbdbe182"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("button_configs", sa.Column("style", sa.String(length=16), nullable=True))
    op.add_column(
        "content",
        sa.Column("link_preview", sa.Boolean(), server_default=sa.text("true"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("content", "link_preview")
    op.drop_column("button_configs", "style")
    # ### end Alembic commands ###
