"""push_subscriptions.locale

Revision ID: 5cf70aa2a938
Revises: e21917c0ba36
Create Date: 2026-07-10 23:03:35.744220

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cf70aa2a938'
down_revision: str | None = 'e21917c0ba36'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('push_subscriptions', sa.Column('locale', sa.String(length=8), server_default='fa', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('push_subscriptions', 'locale')
    # ### end Alembic commands ###
