"""site tables (devices, claims, rewards, push subs, messages, landing pages)

Revision ID: e21917c0ba36
Revises: b8e4c2f5a611
Create Date: 2026-07-10 20:26:12.430050

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e21917c0ba36'
down_revision: str | None = 'b8e4c2f5a611'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_devices',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='available', nullable=False),
    sa.Column('site_panel_username', sa.String(length=64), nullable=True),
    sa.Column('last_claim_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('referral_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('referred_by', sa.String(length=36), nullable=True),
    sa.Column('streak_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_streak_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fingerprint_hash', sa.String(length=64), nullable=True),
    sa.Column('ip_bucket', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_site_devices_referred_by'), 'site_devices', ['referred_by'], unique=False)
    op.create_table('site_landing_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('meta_description', sa.String(length=320), server_default='', nullable=False),
    sa.Column('heading', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), server_default='', nullable=False),
    sa.Column('location_remark', sa.String(length=128), nullable=True),
    sa.Column('published', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', 'locale', name='uq_site_landing_slug_locale')
    )
    op.create_index(op.f('ix_site_landing_pages_slug'), 'site_landing_pages', ['slug'], unique=False)
    op.create_table('site_messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('reply_handle', sa.String(length=200), nullable=True),
    sa.Column('locale', sa.String(length=8), server_default='fa', nullable=False),
    sa.Column('device_uuid', sa.String(length=36), nullable=True),
    sa.Column('read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_uuid', sa.String(length=36), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=False),
    sa.Column('p256dh', sa.String(length=255), nullable=False),
    sa.Column('auth', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_uuid'], ['site_devices.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint', name='uq_push_subscription_endpoint')
    )
    op.create_index(op.f('ix_push_subscriptions_device_uuid'), 'push_subscriptions', ['device_uuid'], unique=False)
    op.create_table('site_claims',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('device_uuid', sa.String(length=36), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_uuid'], ['site_devices.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_claims_device_uuid'), 'site_claims', ['device_uuid'], unique=False)
    op.create_table('site_rewards',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('device_uuid', sa.String(length=36), nullable=False),
    sa.Column('reward_type', sa.String(length=32), nullable=False),
    sa.Column('amount_mb', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_uuid'], ['site_devices.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_uuid', 'reward_type', name='uq_site_reward_device_type')
    )
    op.create_index(op.f('ix_site_rewards_device_uuid'), 'site_rewards', ['device_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_rewards_device_uuid'), table_name='site_rewards')
    op.drop_table('site_rewards')
    op.drop_index(op.f('ix_site_claims_device_uuid'), table_name='site_claims')
    op.drop_table('site_claims')
    op.drop_index(op.f('ix_push_subscriptions_device_uuid'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_table('site_messages')
    op.drop_index(op.f('ix_site_landing_pages_slug'), table_name='site_landing_pages')
    op.drop_table('site_landing_pages')
    op.drop_index(op.f('ix_site_devices_referred_by'), table_name='site_devices')
    op.drop_table('site_devices')
    # ### end Alembic commands ###
